name: Deploy Python App to CapRover

on:
  push:
    branches: ["main"]
          
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to CapRover
        uses: caprover/github-action@v1.3.2
        with:
          # URL completa de tu servidor CapRover (ej: https://captain.miservidor.com)
          #server: http://testapp.capradich.mywire.org/
          #server: http://captain.capradich.mywire.org/
          # El nombre de la app tal como aparece en el panel de CapRover
          #app: testapp
          # Usa el secreto que creaste en GitHub
          #token: ${{ d131f040aa97680a5043d0a0894b34fab4162c69a0ca7c230402d029586ea6e0 }}
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'